#############################################################################
# Makefile for building: gradebook
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sat Dec 29 15:33:59 2012
# Project:  gradebook.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile gradebook.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I/usr/bin/boost_1_51_0 -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu /usr/bin/boost_1_51_0/boost/lib/libboost_regex.a -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = addassignmentdialog.cpp \
		addgradebookdialog.cpp \
		assignment.cpp \
		deletegradebookdialog.cpp \
		editstudentdialog.cpp \
		gradbookmanager.cpp \
		gradebook.cpp \
		gradebookmaingui.cpp \
		gradebookmaintest.cpp \
		gradebookmanager.cpp \
		student.cpp \
		viewclassdialog.cpp \
		addstudentdialog.cpp \
		deletestudentdialog.cpp \
		editallassignmentsdialog.cpp \
		deleteallassignmentdialog.cpp \
		addallextrapoints.cpp \
		viewallgrades.cpp \
		editscoresdialog.cpp moc_addassignmentdialog.cpp \
		moc_addgradebookdialog.cpp \
		moc_deletegradebookdialog.cpp \
		moc_editstudentdialog.cpp \
		moc_gradebookmaingui.cpp \
		moc_viewclassdialog.cpp \
		moc_addstudentdialog.cpp \
		moc_deletestudentdialog.cpp \
		moc_editallassignmentsdialog.cpp \
		moc_deleteallassignmentdialog.cpp \
		moc_addallextrapoints.cpp \
		moc_editscoresdialog.cpp
OBJECTS       = addassignmentdialog.o \
		addgradebookdialog.o \
		assignment.o \
		deletegradebookdialog.o \
		editstudentdialog.o \
		gradbookmanager.o \
		gradebook.o \
		gradebookmaingui.o \
		gradebookmaintest.o \
		gradebookmanager.o \
		student.o \
		viewclassdialog.o \
		addstudentdialog.o \
		deletestudentdialog.o \
		editallassignmentsdialog.o \
		deleteallassignmentdialog.o \
		addallextrapoints.o \
		viewallgrades.o \
		editscoresdialog.o \
		moc_addassignmentdialog.o \
		moc_addgradebookdialog.o \
		moc_deletegradebookdialog.o \
		moc_editstudentdialog.o \
		moc_gradebookmaingui.o \
		moc_viewclassdialog.o \
		moc_addstudentdialog.o \
		moc_deletestudentdialog.o \
		moc_editallassignmentsdialog.o \
		moc_deleteallassignmentdialog.o \
		moc_addallextrapoints.o \
		moc_editscoresdialog.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		gradebook.pro
QMAKE_TARGET  = gradebook
DESTDIR       = 
TARGET        = gradebook

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: gradebook.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile gradebook.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile gradebook.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/gradebook1.0.0 || $(MKDIR) .tmp/gradebook1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/gradebook1.0.0/ && $(COPY_FILE) --parents addassignmentdialog.h addgradebookdialog.h assignment.h deletegradebookdialog.h editstudentdialog.h gradebook.h gradebookmaingui.h gradebookmanager.h student.h viewclassdialog.h addstudentdialog.h deletestudentdialog.h editallassignmentsdialog.h deleteallassignmentdialog.h addallextrapoints.h viewallgrades.h editscoresdialog.h .tmp/gradebook1.0.0/ && $(COPY_FILE) --parents addassignmentdialog.cpp addgradebookdialog.cpp assignment.cpp deletegradebookdialog.cpp editstudentdialog.cpp gradbookmanager.cpp gradebook.cpp gradebookmaingui.cpp gradebookmaintest.cpp gradebookmanager.cpp student.cpp viewclassdialog.cpp addstudentdialog.cpp deletestudentdialog.cpp editallassignmentsdialog.cpp deleteallassignmentdialog.cpp addallextrapoints.cpp viewallgrades.cpp editscoresdialog.cpp .tmp/gradebook1.0.0/ && (cd `dirname .tmp/gradebook1.0.0` && $(TAR) gradebook1.0.0.tar gradebook1.0.0 && $(COMPRESS) gradebook1.0.0.tar) && $(MOVE) `dirname .tmp/gradebook1.0.0`/gradebook1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/gradebook1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_addassignmentdialog.cpp moc_addgradebookdialog.cpp moc_deletegradebookdialog.cpp moc_editstudentdialog.cpp moc_gradebookmaingui.cpp moc_viewclassdialog.cpp moc_addstudentdialog.cpp moc_deletestudentdialog.cpp moc_editallassignmentsdialog.cpp moc_deleteallassignmentdialog.cpp moc_addallextrapoints.cpp moc_editscoresdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_addassignmentdialog.cpp moc_addgradebookdialog.cpp moc_deletegradebookdialog.cpp moc_editstudentdialog.cpp moc_gradebookmaingui.cpp moc_viewclassdialog.cpp moc_addstudentdialog.cpp moc_deletestudentdialog.cpp moc_editallassignmentsdialog.cpp moc_deleteallassignmentdialog.cpp moc_addallextrapoints.cpp moc_editscoresdialog.cpp
moc_addassignmentdialog.cpp: gradebook.h \
		student.h \
		assignment.h \
		addassignmentdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) addassignmentdialog.h -o moc_addassignmentdialog.cpp

moc_addgradebookdialog.cpp: gradebookmanager.h \
		addgradebookdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) addgradebookdialog.h -o moc_addgradebookdialog.cpp

moc_deletegradebookdialog.cpp: gradebookmanager.h \
		deletegradebookdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) deletegradebookdialog.h -o moc_deletegradebookdialog.cpp

moc_editstudentdialog.cpp: student.h \
		assignment.h \
		gradebook.h \
		addassignmentdialog.h \
		editstudentdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) editstudentdialog.h -o moc_editstudentdialog.cpp

moc_gradebookmaingui.cpp: gradebook.h \
		student.h \
		assignment.h \
		addgradebookdialog.h \
		gradebookmanager.h \
		viewclassdialog.h \
		editstudentdialog.h \
		addassignmentdialog.h \
		addstudentdialog.h \
		deletestudentdialog.h \
		editallassignmentsdialog.h \
		deleteallassignmentdialog.h \
		addallextrapoints.h \
		viewallgrades.h \
		editscoresdialog.h \
		deletegradebookdialog.h \
		gradebookmaingui.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) gradebookmaingui.h -o moc_gradebookmaingui.cpp

moc_viewclassdialog.cpp: gradebook.h \
		student.h \
		assignment.h \
		editstudentdialog.h \
		addassignmentdialog.h \
		addstudentdialog.h \
		deletestudentdialog.h \
		editallassignmentsdialog.h \
		deleteallassignmentdialog.h \
		addallextrapoints.h \
		viewallgrades.h \
		editscoresdialog.h \
		viewclassdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) viewclassdialog.h -o moc_viewclassdialog.cpp

moc_addstudentdialog.cpp: gradebook.h \
		student.h \
		assignment.h \
		addstudentdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) addstudentdialog.h -o moc_addstudentdialog.cpp

moc_deletestudentdialog.cpp: gradebook.h \
		student.h \
		assignment.h \
		deletestudentdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) deletestudentdialog.h -o moc_deletestudentdialog.cpp

moc_editallassignmentsdialog.cpp: gradebook.h \
		student.h \
		assignment.h \
		editallassignmentsdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) editallassignmentsdialog.h -o moc_editallassignmentsdialog.cpp

moc_deleteallassignmentdialog.cpp: gradebook.h \
		student.h \
		assignment.h \
		deleteallassignmentdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) deleteallassignmentdialog.h -o moc_deleteallassignmentdialog.cpp

moc_addallextrapoints.cpp: gradebook.h \
		student.h \
		assignment.h \
		addallextrapoints.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) addallextrapoints.h -o moc_addallextrapoints.cpp

moc_editscoresdialog.cpp: gradebook.h \
		student.h \
		assignment.h \
		editscoresdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) editscoresdialog.h -o moc_editscoresdialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

addassignmentdialog.o: addassignmentdialog.cpp addassignmentdialog.h \
		gradebook.h \
		student.h \
		assignment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addassignmentdialog.o addassignmentdialog.cpp

addgradebookdialog.o: addgradebookdialog.cpp addgradebookdialog.h \
		gradebookmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addgradebookdialog.o addgradebookdialog.cpp

assignment.o: assignment.cpp assignment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o assignment.o assignment.cpp

deletegradebookdialog.o: deletegradebookdialog.cpp deletegradebookdialog.h \
		gradebookmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o deletegradebookdialog.o deletegradebookdialog.cpp

editstudentdialog.o: editstudentdialog.cpp editstudentdialog.h \
		student.h \
		assignment.h \
		gradebook.h \
		addassignmentdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editstudentdialog.o editstudentdialog.cpp

gradbookmanager.o: gradbookmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gradbookmanager.o gradbookmanager.cpp

gradebook.o: gradebook.cpp gradebook.h \
		student.h \
		assignment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gradebook.o gradebook.cpp

gradebookmaingui.o: gradebookmaingui.cpp gradebookmaingui.h \
		gradebook.h \
		student.h \
		assignment.h \
		addgradebookdialog.h \
		gradebookmanager.h \
		viewclassdialog.h \
		editstudentdialog.h \
		addassignmentdialog.h \
		addstudentdialog.h \
		deletestudentdialog.h \
		editallassignmentsdialog.h \
		deleteallassignmentdialog.h \
		addallextrapoints.h \
		viewallgrades.h \
		editscoresdialog.h \
		deletegradebookdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gradebookmaingui.o gradebookmaingui.cpp

gradebookmaintest.o: gradebookmaintest.cpp gradebookmaingui.h \
		gradebook.h \
		student.h \
		assignment.h \
		addgradebookdialog.h \
		gradebookmanager.h \
		viewclassdialog.h \
		editstudentdialog.h \
		addassignmentdialog.h \
		addstudentdialog.h \
		deletestudentdialog.h \
		editallassignmentsdialog.h \
		deleteallassignmentdialog.h \
		addallextrapoints.h \
		viewallgrades.h \
		editscoresdialog.h \
		deletegradebookdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gradebookmaintest.o gradebookmaintest.cpp

gradebookmanager.o: gradebookmanager.cpp gradebookmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gradebookmanager.o gradebookmanager.cpp

student.o: student.cpp student.h \
		assignment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o student.o student.cpp

viewclassdialog.o: viewclassdialog.cpp viewclassdialog.h \
		gradebook.h \
		student.h \
		assignment.h \
		editstudentdialog.h \
		addassignmentdialog.h \
		addstudentdialog.h \
		deletestudentdialog.h \
		editallassignmentsdialog.h \
		deleteallassignmentdialog.h \
		addallextrapoints.h \
		viewallgrades.h \
		editscoresdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewclassdialog.o viewclassdialog.cpp

addstudentdialog.o: addstudentdialog.cpp addstudentdialog.h \
		gradebook.h \
		student.h \
		assignment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addstudentdialog.o addstudentdialog.cpp

deletestudentdialog.o: deletestudentdialog.cpp deletestudentdialog.h \
		gradebook.h \
		student.h \
		assignment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o deletestudentdialog.o deletestudentdialog.cpp

editallassignmentsdialog.o: editallassignmentsdialog.cpp editallassignmentsdialog.h \
		gradebook.h \
		student.h \
		assignment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editallassignmentsdialog.o editallassignmentsdialog.cpp

deleteallassignmentdialog.o: deleteallassignmentdialog.cpp deleteallassignmentdialog.h \
		gradebook.h \
		student.h \
		assignment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o deleteallassignmentdialog.o deleteallassignmentdialog.cpp

addallextrapoints.o: addallextrapoints.cpp addallextrapoints.h \
		gradebook.h \
		student.h \
		assignment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addallextrapoints.o addallextrapoints.cpp

viewallgrades.o: viewallgrades.cpp viewallgrades.h \
		gradebook.h \
		student.h \
		assignment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewallgrades.o viewallgrades.cpp

editscoresdialog.o: editscoresdialog.cpp editscoresdialog.h \
		gradebook.h \
		student.h \
		assignment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editscoresdialog.o editscoresdialog.cpp

moc_addassignmentdialog.o: moc_addassignmentdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addassignmentdialog.o moc_addassignmentdialog.cpp

moc_addgradebookdialog.o: moc_addgradebookdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addgradebookdialog.o moc_addgradebookdialog.cpp

moc_deletegradebookdialog.o: moc_deletegradebookdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_deletegradebookdialog.o moc_deletegradebookdialog.cpp

moc_editstudentdialog.o: moc_editstudentdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editstudentdialog.o moc_editstudentdialog.cpp

moc_gradebookmaingui.o: moc_gradebookmaingui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gradebookmaingui.o moc_gradebookmaingui.cpp

moc_viewclassdialog.o: moc_viewclassdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewclassdialog.o moc_viewclassdialog.cpp

moc_addstudentdialog.o: moc_addstudentdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addstudentdialog.o moc_addstudentdialog.cpp

moc_deletestudentdialog.o: moc_deletestudentdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_deletestudentdialog.o moc_deletestudentdialog.cpp

moc_editallassignmentsdialog.o: moc_editallassignmentsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editallassignmentsdialog.o moc_editallassignmentsdialog.cpp

moc_deleteallassignmentdialog.o: moc_deleteallassignmentdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_deleteallassignmentdialog.o moc_deleteallassignmentdialog.cpp

moc_addallextrapoints.o: moc_addallextrapoints.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addallextrapoints.o moc_addallextrapoints.cpp

moc_editscoresdialog.o: moc_editscoresdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editscoresdialog.o moc_editscoresdialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

